substitutions:
  _REGION: us-central1
  _ARTIFACT_REPO: greetup
  _IMAGE: client
  _SERVICE: client
  _PORT: "3000"
  _CPU: "1"
  _MEMORY: 512Mi
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "5"
  _NEXT_PUBLIC_API_BASE_URL: https://dev-api.greetup.club/api
  _NEXT_PUBLIC_SOCKET_SERVER_URL: https://dev-api.greetup.club
  _NEXT_PUBLIC_RTC_SOCKET_URL: https://rtc.dev.greetup.club
  _NEXT_PUBLIC_APP_URL: https://dev.greetup.club

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    dir: client
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE}:$SHORT_SHA
      - --build-arg
      - NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}
      - --build-arg
      - NEXT_PUBLIC_SOCKET_SERVER_URL=${_NEXT_PUBLIC_SOCKET_SERVER_URL}
      - --build-arg
      - NEXT_PUBLIC_RTC_SOCKET_URL=${_NEXT_PUBLIC_RTC_SOCKET_URL}
      - --build-arg
      - NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE}:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - ${_PORT}
      - --cpu
      - ${_CPU}
      - --memory
      - ${_MEMORY}
      - --min-instances
      - ${_MIN_INSTANCES}
      - --max-instances
      - ${_MAX_INSTANCES}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE}:$SHORT_SHA
