substitutions:
  _REGION: us-central1
  _ARTIFACT_REPO: greetup
  _IMAGE: matching-service

options:
  logging: CLOUD_LOGGING_ONLY
  _SERVICE: matching-service
  _PORT: "5060"
  _CPU: "1"
  _MEMORY: 512Mi
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "10"

steps:
  - name: gcr.io/cloud-builders/docker
    dir: matching-service
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE}:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE}:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --no-allow-unauthenticated
      - --port
      - ${_PORT}
      - --cpu
      - ${_CPU}
      - --memory
      - ${_MEMORY}
      - --min-instances
      - ${_MIN_INSTANCES}
      - --max-instances
      - ${_MAX_INSTANCES}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE}:$SHORT_SHA
