type DetailMode = "none" | "language" | "topic" | "optional_topic";

type SessionActivitySeedRow = {
  name: string;
  displayName: string;
  description: string;
  emoji: string;
  detailMode: DetailMode;
  detailLabel: string | null;
  detailPlaceholder: string | null;
  detailMaxLength: number;
  sortOrder: number;
  isActive: boolean;
  allowInMatchPrep: boolean;
  allowInSpace: boolean;
  detailRequired: boolean;
};

export const SESSION_ACTIVITY_SEED: SessionActivitySeedRow[] = [
  {
    name: "play_chess",
    displayName: "Play chess",
    description: "Play a game together (1:1 only)",
    emoji: "♟️",
    detailMode: "none",
    detailLabel: null,
    detailPlaceholder: null,
    detailMaxLength: 80,
    sortOrder: 0,
    isActive: true,
    allowInMatchPrep: true,
    allowInSpace: false,
    detailRequired: false,
  },
  {
    name: "language_practice",
    displayName: "Language practice",
    description: "Practice speaking a language",
    emoji: "🗣️",
    detailMode: "language",
    detailLabel: "Which language?",
    detailPlaceholder: "e.g. Spanish, Hindi, Japanese",
    detailMaxLength: 80,
    sortOrder: 1,
    isActive: true,
    allowInMatchPrep: true,
    allowInSpace: true,
    detailRequired: true,
  },
  {
    name: "startup_ideas",
    displayName: "Startup & business ideas",
    description: "Discuss or validate startup and business ideas",
    emoji: "🚀",
    detailMode: "none",
    detailLabel: null,
    detailPlaceholder: null,
    detailMaxLength: 80,
    sortOrder: 2,
    isActive: true,
    allowInMatchPrep: true,
    allowInSpace: true,
    detailRequired: false,
  },
  {
    name: "vent",
    displayName: "Vent",
    description: "Get something off your chest",
    emoji: "💨",
    detailMode: "topic",
    detailLabel: "What's on your mind?",
    detailPlaceholder: "e.g. work stress, relationships",
    detailMaxLength: 80,
    sortOrder: 3,
    isActive: true,
    allowInMatchPrep: true,
    allowInSpace: true,
    detailRequired: true,
  },
  {
    name: "anxiety_talk",
    displayName: "Talk through anxiety",
    description:
      "When your mind won't quiet down — talk it out with someone who'll listen. Peer support, not professional advice.",
    emoji: "🫂",
    detailMode: "optional_topic",
    detailLabel: "What's feeling heavy? (optional)",
    detailPlaceholder: "e.g. work panic, social stuff, can't switch off",
    detailMaxLength: 80,
    sortOrder: 4,
    isActive: true,
    allowInMatchPrep: true,
    allowInSpace: true,
    detailRequired: false,
  },
  {
    name: "feeling_low",
    displayName: "Feeling low",
    description:
      "For sad or heavy days — quiet company and honest talk. Not therapy; just someone there with you.",
    emoji: "💙",
    detailMode: "optional_topic",
    detailLabel: "Want to share what's going on? (optional)",
    detailPlaceholder: "Only if you want — or leave blank",
    detailMaxLength: 80,
    sortOrder: 5,
    isActive: true,
    allowInMatchPrep: true,
    allowInSpace: true,
    detailRequired: false,
  },
  {
    name: "open_up",
    displayName: "Open up",
    description:
      "Share something you've been holding in — at your pace, with someone ready to listen without judging.",
    emoji: "🗝️",
    detailMode: "topic",
    detailLabel: "What do you want to open up about?",
    detailPlaceholder: "Something you've kept to yourself lately",
    detailMaxLength: 80,
    sortOrder: 6,
    isActive: false,
    allowInMatchPrep: true,
    allowInSpace: true,
    detailRequired: true,
  },
  {
    name: "yap",
    displayName: "Yap",
    description: "Casual open-ended chat about anything",
    emoji: "🗯️",
    detailMode: "topic",
    detailLabel: "What do you want to yap about?",
    detailPlaceholder: "Anything goes — keep it short",
    detailMaxLength: 80,
    sortOrder: 7,
    isActive: true,
    allowInMatchPrep: true,
    allowInSpace: true,
    detailRequired: false,
  },
  {
    name: "media_chat",
    displayName: "Movies, sports & books",
    description: "Talk about movies, sports, or books",
    emoji: "🎬",
    detailMode: "topic",
    detailLabel: "What do you want to talk about?",
    detailPlaceholder: "e.g. IPL, Dune, sci-fi books",
    detailMaxLength: 80,
    sortOrder: 8,
    isActive: true,
    allowInMatchPrep: true,
    allowInSpace: true,
    detailRequired: true,
  },
  {
    name: "topic_discuss",
    displayName: "Discuss a topic",
    description: "AI, tech, or any topic — discuss or debate",
    emoji: "💡",
    detailMode: "topic",
    detailLabel: "Topic",
    detailPlaceholder: "e.g. AI agents, climate, philosophy",
    detailMaxLength: 80,
    sortOrder: 9,
    isActive: true,
    allowInMatchPrep: true,
    allowInSpace: true,
    detailRequired: true,
  },
  {
    name: "truth_or_dare",
    displayName: "Truth or Dare",
    description: "Play truth or dare together",
    emoji: "🎲",
    detailMode: "optional_topic",
    detailLabel: "Session title (optional)",
    detailPlaceholder: "e.g. Spicy edition",
    detailMaxLength: 80,
    sortOrder: 10,
    isActive: false,
    allowInMatchPrep: true,
    allowInSpace: true,
    detailRequired: false,
  },
  {
    name: "study_together",
    displayName: "Study together",
    description: "Focus and study alongside someone",
    emoji: "📚",
    detailMode: "optional_topic",
    detailLabel: "Subject or focus (optional)",
    detailPlaceholder: "e.g. UPSC, calculus, React",
    detailMaxLength: 80,
    sortOrder: 11,
    isActive: true,
    allowInMatchPrep: true,
    allowInSpace: true,
    detailRequired: false,
  },
];
